#######################
# TMUX Configuration  #
#######################

# Fix colors and enable true color (24-bit) support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# increase scrollback history
set -g history-limit 5000

# decrease command delay to increase vim responsiveness
set -s escape-time 0

# pass through clipboard cmds
set -s set-clipboard on

#pane switching using the mouse
set -g mouse on

# Enable undercurl support for LSP diagnostics
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setqc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%m'

#vi-like movement in copy mode
#setw -g mode-keys vi
#unbind p
#bind p paste-buffer
#bind-key -t vi-copy v begin-selection
#bind-key -t vi-copy y copy-selection
