# Uncomment if bluetooth headset is mixing up high quality music with a phone call.
# Affects Ubuntu. wireplumber gets confused and tries to auto switch to phone call mode.
# HSP/HFP=Audio call  A2DP=High quality audio stream
# After disabling: systemctl --user restart wireplumber
#wireplumber.settings = {
#    bluetooth.autoswitch-to-headset-profile = false
#}
